version: "3.9"

services:
  postgres:
    image: postgres:alpine
    container_name: topocart-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/db.sql:/docker-entrypoint-initdb.d/db.sql
    restart: always
